baseurl = "https://aaronkjones.com"
title = "Aaron Jones"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Aaron Jones"
disqusshortname = ""
pluralizelisttitles = false
googleAnalytics = "UA-114562131-1"

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Aaron Jones"
copyright = "Copyright © 2019"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = ""
faviconfile = "img/favicon-32x32.png"
highlightjs = true
progressively = true
share = true
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
latestpostcount = 5
github = "aaronkjones"
email = "aaronkjones@mailbox.org"
#linkedin = "john-example-aa80ue8è"
twitter = "jonesak"
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
commentoHost = "cdn.commento.io"
# githubRepo = "githubUsername/repositoryName/tree/master"
small_banner_logo = true

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"