[build] 
  publish = "public"
  command = "hugo -t hugo-nuo"

[context.production.environment]
  HUGO_VERSION = "0.54.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.55.0"